services:
  app:
    image: ghcr.io/bipprojectbali/sort:stg-latest
    container_name: sort
    restart: always
    cpus: "0.5"
    mem_limit: 1g
    mem_reservation: 512m
    pids_limit: 512
    cpu_shares: 512
    shm_size: "512mb"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public-net"
      - "traefik.http.routers.sort-stg.rule=Host(`sort.wibudev.com`)"
      - "traefik.http.routers.sort-stg.entrypoints=websecure"
      - "traefik.http.routers.sort-stg.tls.certresolver=letsencrypt"
      - "traefik.http.routers.sort-stg.service=sort-stg"
      - "traefik.http.services.sort-stg.loadbalancer.server.port=3000"
    networks:
      - public-net
      - postgres-net

networks:
  postgres-net:
    external: true
  public-net:
    external: true 